public class Calculations{
    //Addition
    public void doSum(){
        integer a=3;
        integer b=5;
        integer c;
        
        c = a+b;
        
        system.debug('Sum of 3 and 5 is:'+c);
    }
    //Substraction
    public void doSub(){
        integer a=3;
        integer b=5;
        integer c;
        
        c = a-b;
        
        system.debug('Substraction of 3 and 5 is:'+c);
    }
    
}